apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-ebs
spec:
  serviceName: "nginx-ebs"
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ebs
  template:
    metadata:
      labels:
        app: nginx-ebs
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: ebs-volume
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: ebs-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 5Gi
