apiVersion: v1
kind: Pod
metadata:
  name: emppod
  labels:
    app: empapp
spec:
  containers:
  - name: i1
    image: centos:7
    command: [/bin/sh,-c,'while true;do X=$[$X+1];echo "<h1>$X</h1>" > /usr/share/nginx/html/index.html;sleep 1;done']
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: empvol
  - name: i2
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: empvol
  volumes:
  - name: empvol
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: testserv
spec:
  type: LoadBalancer
  selector:
    app: empapp
  ports:
  - port: 80
    targetPort: 80