apiVersion: v1
kind: Pod
metadata:
  name: hostpod
  labels:
    app: hostpod
spec:
  containers:
  - name: i1
    image: centos:7
    command: [/bin/sh,-c,'while true;do X=$[$X+1];echo "<h1>$X</h1>" > /usr/share/nginx/html/index.html;sleep 1;done']
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: hostvol
  - name: i2
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: hostvol
  volumes:
  - name: hostvol
    hostPath:
      path: /root/data