apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpadep
  template:
    metadata:
      labels:
        app: hpadep
    spec:
      containers:
      - name: testdep
        image: nginx
        resources:
          requests:
            cpu: 100m
          limits: 
            cpu: 200m

