apiVersion: v1
kind: ConfigMap
metadata:
  name: myconf
data:
  username: someusername-mod1
  uid: someuid-mod1
---
apiVersion: v1
kind: Pod
metadata:
  name: confpod
spec:
  containers:
  - name: myapp
    image: centos:7
    command: [/bin/sh,-c,"sleep 3600"]
    env:
    - name: e1
      valueFrom: 
        configMapKeyRef:
          name: myconf
          key: username
    - name: e2
      valueFrom: 
        configMapKeyRef:
          name: myconf
          key: uid
    

