apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myds
spec:
  selector:
    matchLabels:
      app: myds
  template:
    metadata:
      labels:
        app: myds
    spec:
      containers:
      - name: myapp
        image: tomcat:8
