apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 3
  template:
    spec:
      containers:
      - name: pi
        image: centos:7
        command: [/bin/sh,-c,"sleep 10"]
      restartPolicy: Never
