apiVersion: v1
kind: ServiceAccount
metadata:
  name: myserviceaccount
  namespace: default 
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::533266971996:role/sa-role-for-eks2
---
apiVersion: v1
kind: Pod
metadata:
  name: mysa
  labels:
    name: mysa
spec:
  serviceAccountName: myserviceaccount
  containers:
  - name: mysa
    image: amazon/aws-cli
    command: [/bin/sh,-c,'sleep 3600']
    
