apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: UGFzc3dvcmRAc29tZXRoaW5n
---
apiVersion: v1
kind: Pod
metadata:
  name: secpod
spec:
  containers:
  - name: myapp
    image: centos:7
    command: [/bin/sh,-c,"sleep 3600"]
    env:
    - name: e1
      valueFrom: 
        secretKeyRef:
          name: mysecret
          key: password