apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mypvc
spec:
 accessModes:
   - ReadWriteOnce
 storageClassName: ebs-gp3
 resources:
   requests:
     storage: 12Gi
---
apiVersion: v1
kind: Pod
metadata:
 name: dynamicpod
spec:
 containers:
 - name: m1
   image: mongo
   volumeMounts:
   - name: myvol
     mountPath: /data/db
 volumes:
 - name: myvol
   persistentVolumeClaim:
     claimName: mypvc
