apiVersion: v1
kind: rolens
metadata:
  name: rolens
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rolens 
  name: role-pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
