apiVersion: v1
kind: Pod
metadata:
  name: taintpod
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "computing"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
