apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testdep
  template:
    metadata:
      labels:
        app: testdep
    spec:
      containers:
      - name: testdep
        image: nginx
        
